### ISSUE TITLE
Target 'check' is not working due to file absence

### ISSUE THREAD

**Issue by jserv** [Kimplul/copyjit#1]
I can build `copyjit` binary via the default target. However, I failed to proceed `make check` because of the following error:
```
./tests/check.sh
make: ./tests/check.sh: Command not found
make: *** [Makefile:98: check] Error 127
```

It seems that directory 'tests' is absent.

**Comment by Kimplul** [comment]
Thanks for the heads up, just pushed some rudimentary checks. `copyjit` also now prints out the calculated value.

Frankly wasn't expecting anyone to pay any attention to this project so it's in a very crude state. Starting to think some of the more exotic architectures look like they might not be trivially fixable so I suspect the whole premise is a bit flawed, should maybe also add a note or something about that.
