### ISSUE TITLE
The generation of `copyjit` executable?

### ISSUE THREAD

**Issue by jserv** [Kimplul/copyjit#2]
File `tests/check.c` was checked in (commit c671d6612be0fb28eea498246c39bb5032afa872), which renders file `src/main.c` pointless for the sake of validation. Does it make sense to keep `src/main.c` and related build targets?

**Comment by Kimplul** [comment]
Assuming `tests/check.c` is expanded with more test cases, then yeah, `src/main.c` is indeed pointless. As it stands, `src/main.c` is arguably a more complete example that does actually 'useful' work.

Probably most notably `tests/check.c` is missing branches, as I haven't added forward references yet. I can try adding them in after work today, probably using something similar to the patching I'm doing in https://github.com/Kimplul/bcgen.

**Comment by Kimplul** [comment]
Busier day than I was expecting, didn't get anything done today. I'll try again tomorrow.

**Comment by Kimplul** [comment]
I added a rudimentary patching mechanism, expanded on `tests/check.c` a little bit and moved `main.c` to `examples`.
`make examples` now builds `examples/copyjit`.
